version: "3"
services:
    web:
        build: .
        ports:
            - "443:443"
        volumes:
            - /apps/certs/gorilla.lk:/apps/certs/gorilla.lk
            - /apps/images/gorilla.lk:/apps/images/gorilla.lk:rw
