version: "3"
services:
    web:
        build: .
        ports:
            - "443:443"
            - "80:80"
        volumes:
            - /apps/logs/web:/app/log:rw
            - /apps/certs/gorilla.lk:/apps/certs/gorilla.lk
            - /apps/images/gorilla.lk:/apps/images/gorilla.lk:rw
            - /apps/files/gorilla.lk:/apps/files/gorilla.lk:rw
