version: "3"
services:
    web:
        build: .
        ports:
            - "443:443"
        volumes:
            - /apps/logs/service:/app/log:r
            - /apps/certs/gorilla.lk:/apps/certs/gorilla.lk:r
